{
 "title": "Aleo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Height Increasing?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aleo_latest_height[5m])"
    }
   ]
  },
  {
   "title": "Latest Timestamp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_peer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Coinbase Target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_coinbase_target", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_latest_height", "legendFormat": "__auto" }
   ]
  }
 ]
}